site_name: Unloaded Activity Docs
site_url: https://unloadedactivity.moono.dev
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - About Unloaded Activity: index.md
  - For players:
      - Config options: players/config.md
  - For developers:
      - Introduction: developers/index.md
      - Adding support: developers/add_support.md
