
unimined.minecraft {
    fabric {
        loader fabric_loader_version
        accessWidener = file("src/main/resources/unloadedactivity${rootProject.aw_namespace}.classtweaker")
    }

    defaultRemapJar = false
    runs.off = true
}

def mc_info = new Properties()

rootDir.listFiles().each { file ->
    if (file.name == "build.properties") {
        mc_info.load(file.newReader())
    }
}

dependencies {
    // Since these are only for compiling,
    // I can mix and match both (neo)forge and fabric versions and game versions.
    // modImplementations are in the loader specific gradle files.
    if (mc_info.MC_VER >= mc_info.MC_1_21_1) {
        compileOnly "maven.modrinth:R2OftAxM:GbNuOZ4S" // 1.21.1-1.3.2

    } else if (mc_info.MC_VER >= mc_info.MC_1_20_1) {
        compileOnly "maven.modrinth:R2OftAxM:CsjS7EkP" // 1.20.1-1.3.2

    } else if (mc_info.MC_VER >= mc_info.MC_1_19_2) {
        compileOnly "maven.modrinth:R2OftAxM:rFTKVUtq" // 1.19.2-1.2.4
    }
}